# Generated by Django 2.1.7 on 2019-02-21 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='descritption',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='descritption',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='subtask',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backoffice.Task'),
            preserve_default=False,
        ),
    ]
